# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ff29e6bd716ea68e7bd348d885c340571efc0f4f2185691a62b8726638e80f6c666bd4259e8a6ea1368a1c38c300fa8fddd06c6dc7bc400e1e266bbdedbd021

test:
  secret_key_base: 944fb136ef6c345bebadd058d4e4942947bd4d249e0c44d5b0d1aebe3c0f124ba9c173aed055ec91f1fad33d7fb83bd6a7497ee04373496abf95dc9ade02f4bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
